version: "3"
services:
  php:
    build:
      context: .
      dockerfile: docker-files/dev/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./lumen:/var/www/html
      - ./sysconfig:/etc/sysconfig
  redis:
    image: isaackuang/redis:5.0.4
    ports:
      - 6379:6379
  postgre:
    image: isaackuang/postgres
    ports:
      - 5432:5432
